
import {Schema, Types, model,mongoose} from "mongoose";
const OrderSchema = new Schema({
    UserId:{
        type:Types.ObjectId,
        required:true,
        ref:'User',
    },
   products:[
    {
        productName:{
            type:String,
            required:true,
        },
        productId:{
            type:Types.ObjectId,
            ref:'Product',
            required:true,
    },
    quantity:{
        type:Number,
        default:1,},
    unitPrice:{
        type:Number,
        required:true,
    },
      finalPrice:{
    type:Number,
    required:true,
      }}
   ],
   couponName:{
    type:String
   },
   finalPrice:{
    type:Number,
    required:true,
    default:0,
   },
   paymentType:{
    type:String,
    default:'cash',
    enum:['cash','card'],
   },
   phoneNumber:{
    type:String,
    required:true,
   },
   address:{
   type:String,
   required:true,},
   status:{
    type:String,
    default:'pending',
    enum:['pending','canceled','confirmed','onWay','deliverd']
   },
   note:String,
   reasonRejected:String,
   updatedBy:{
    type:Types.ObjectId,
    ref:'User',
},
      },
    {
        timestamps:true,
    });

    const OrderModel =  mongoose.models.Order||model('Order',OrderSchema);
    export default OrderModel;